/**
 * {{CLI_NAME}} — {{CLI_PURPOSE}}
 *
 * Agent-first CLI generated by cli-forge. This scaffold enforces the
 * Agent-First CLI Contract: --json everywhere, non-interactive,
 * deterministic, fast-failure, --dry-run on destructive ops, --help
 * is the schema.
 *
 * Do NOT add prompts, wizards, spinners, or color codes. The consumer
 * is an AI agent, not a human at a terminal.
 *
 * Usage:
 *   {{CLI_NAME}} --help
 *   {{CLI_NAME}} {{EXAMPLE_COMMAND}} --json
 *
 * Environment:
 *   {{ENV_TOKEN_NAME}}   Required. API token for {{API_BASE_URL}}.
 */

import { Command } from "commander";
import { ApiClient, ApiError } from "./client";

// -------- Global output helpers (Agent-First Contract) ----------------------

type AnyValue = unknown;

function isTty(): boolean {
  return Boolean(process.stdout.isTTY);
}

function emit(
  payload: AnyValue,
  opts: { jsonFlag: boolean; quiet: boolean },
): void {
  if (opts.quiet) {
    if (Array.isArray(payload)) {
      for (const item of payload) process.stdout.write(`${bare(item)}\n`);
    } else {
      process.stdout.write(`${bare(payload)}\n`);
    }
    return;
  }

  if (opts.jsonFlag || !isTty()) {
    process.stdout.write(`${JSON.stringify(payload, sortReplacer)}\n`);
    return;
  }

  // Human fallback — plain, no colors.
  process.stdout.write(`${JSON.stringify(payload, sortReplacer, 2)}\n`);
}

function bare(item: AnyValue): string {
  if (item && typeof item === "object" && !Array.isArray(item)) {
    const rec = item as Record<string, unknown>;
    for (const k of ["id", "name", "slug", "uuid"]) {
      if (k in rec) return String(rec[k]);
    }
    return JSON.stringify(rec, sortReplacer);
  }
  return String(item);
}

function sortReplacer(_key: string, value: unknown): unknown {
  if (value && typeof value === "object" && !Array.isArray(value)) {
    const sorted: Record<string, unknown> = {};
    for (const k of Object.keys(value as Record<string, unknown>).sort()) {
      sorted[k] = (value as Record<string, unknown>)[k];
    }
    return sorted;
  }
  return value;
}

function die(msg: string, hint?: string, code = 2): never {
  process.stderr.write(`Error: ${msg}\n`);
  if (hint) process.stderr.write(`Hint: ${hint}\n`);
  process.exit(code);
}

function requireEnv(name: string): string {
  const val = process.env[name];
  if (!val) {
    die(
      `environment variable ${name} is not set`,
      `export ${name}=<your-token> and retry`,
    );
  }
  return val as string;
}

function getClient(): ApiClient {
  return new ApiClient({
    baseUrl: process.env["{{ENV_BASE_URL_NAME}}"] ?? "{{API_BASE_URL}}",
    token: requireEnv("{{ENV_TOKEN_NAME}}"),
  });
}

// -------- Program -----------------------------------------------------------

const program = new Command();
program
  .name("{{CLI_NAME}}")
  .description("{{CLI_PURPOSE}}")
  .showHelpAfterError()
  .exitOverride();

// Global flags (registered on every command)
type GlobalOpts = { json?: boolean; quiet?: boolean; dryRun?: boolean };

function withGlobals(cmd: Command): Command {
  return cmd
    .option("--json", "JSON output (default when piped)")
    .option("--quiet", "One bare value per line")
    .option("--dry-run", "Print the request, do not execute");
}

// -------- Commands ----------------------------------------------------------

withGlobals(
  program
    .command("{{EXAMPLE_COMMAND}}")
    .description("{{EXAMPLE_COMMAND_HELP}}")
    .requiredOption("--name <name>", "Resource name. Required.")
    .option("--limit <n>", "Max results. Default 20.", "20"),
).action(
  async (
    opts: GlobalOpts & { name: string; limit: string },
  ): Promise<void> => {
    const limit = Number.parseInt(opts.limit, 10);
    if (Number.isNaN(limit)) {
      die("--limit must be an integer", "e.g. --limit 20");
    }

    if (opts.dryRun) {
      emit(
        {
          method: "GET",
          path: "/{{EXAMPLE_COMMAND}}",
          params: { name: opts.name, limit },
        },
        { jsonFlag: true, quiet: false },
      );
      return;
    }

    try {
      const result = await getClient().example({ name: opts.name, limit });
      emit(result, {
        jsonFlag: Boolean(opts.json),
        quiet: Boolean(opts.quiet),
      });
    } catch (err) {
      if (err instanceof ApiError) {
        die(err.message, err.hint, err.exitCode);
      }
      throw err;
    }
  },
);

// Add more commands here. One .command() per tool. Keep it flat.

async function main(): Promise<void> {
  try {
    await program.parseAsync(process.argv);
  } catch (err) {
    // commander throws on exitOverride — surface as fast-fail.
    if (err instanceof Error) die(err.message);
    throw err;
  }
}

main();
