"""
{{CLI_NAME}} — {{CLI_PURPOSE}}

Agent-first CLI generated by cli-forge. This scaffold enforces the
Agent-First CLI Contract: --json everywhere, non-interactive,
deterministic, fast-failure, --dry-run on destructive ops, --help
is the schema.

Do NOT add prompts, wizards, spinners, or color codes. The consumer
is an AI agent, not a human at a terminal.

Usage:
    {{CLI_NAME}} --help
    {{CLI_NAME}} {{EXAMPLE_COMMAND}} --json

Environment:
    {{ENV_TOKEN_NAME}}   Required. API token for {{API_BASE_URL}}.
"""
from __future__ import annotations

import json
import os
import sys
from typing import Any

import typer

from .client import ApiClient, ApiError

app = typer.Typer(
    name="{{CLI_NAME}}",
    help="{{CLI_PURPOSE}}",
    no_args_is_help=True,
    add_completion=False,  # shell completion is a later concern
    pretty_exceptions_enable=False,  # agents read JSON, not tracebacks
)


# -------- Global output helpers (Agent-First Contract) -----------------------


def _is_tty() -> bool:
    return sys.stdout.isatty()


def emit(payload: Any, *, json_flag: bool, quiet: bool) -> None:
    """
    Canonical output. --json is default when not a TTY.
    --quiet prints one bare value per line, pipeable.
    """
    if quiet:
        if isinstance(payload, list):
            for item in payload:
                sys.stdout.write(f"{_bare(item)}\n")
        else:
            sys.stdout.write(f"{_bare(payload)}\n")
        return

    if json_flag or not _is_tty():
        sys.stdout.write(json.dumps(payload, sort_keys=True, default=str) + "\n")
        return

    # Human fallback — still plain, no colors.
    sys.stdout.write(json.dumps(payload, sort_keys=True, indent=2, default=str) + "\n")


def _bare(item: Any) -> str:
    if isinstance(item, dict):
        # Pick the most ID-like key
        for k in ("id", "name", "slug", "uuid"):
            if k in item:
                return str(item[k])
        return json.dumps(item, sort_keys=True, default=str)
    return str(item)


def die(msg: str, *, hint: str | None = None, code: int = 2) -> None:
    """Fast-fail with actionable error. Exit code 2 = usage error."""
    sys.stderr.write(f"Error: {msg}\n")
    if hint:
        sys.stderr.write(f"Hint: {hint}\n")
    raise typer.Exit(code=code)


def require_env(name: str) -> str:
    val = os.environ.get(name)
    if not val:
        die(
            f"environment variable {name} is not set",
            hint=f"export {name}=<your-token> and retry",
        )
    return val  # type: ignore[return-value]


# -------- Client factory -----------------------------------------------------


def get_client() -> ApiClient:
    return ApiClient(
        base_url=os.environ.get("{{ENV_BASE_URL_NAME}}", "{{API_BASE_URL}}"),
        token=require_env("{{ENV_TOKEN_NAME}}"),
    )


# -------- Commands -----------------------------------------------------------


@app.command("{{EXAMPLE_COMMAND}}")
def example_command(
    name: str = typer.Option(..., "--name", help="Resource name. Required."),
    limit: int = typer.Option(20, "--limit", help="Max results. Default 20."),
    json_flag: bool = typer.Option(False, "--json", help="JSON output (default when piped)."),
    quiet: bool = typer.Option(False, "--quiet", help="One bare value per line."),
    dry_run: bool = typer.Option(False, "--dry-run", help="Print the request, do not execute."),
) -> None:
    """
    {{EXAMPLE_COMMAND_HELP}}

    Example:
        {{CLI_NAME}} {{EXAMPLE_COMMAND}} --name foo --json
    """
    if dry_run:
        emit(
            {"method": "GET", "path": f"/{{EXAMPLE_COMMAND}}", "params": {"name": name, "limit": limit}},
            json_flag=True,
            quiet=False,
        )
        raise typer.Exit(code=0)

    try:
        result = get_client().example(name=name, limit=limit)
    except ApiError as e:
        die(str(e), hint=e.hint, code=e.exit_code)

    emit(result, json_flag=json_flag, quiet=quiet)


# Add more commands here. One function per command. Keep it flat.


def main() -> None:
    app()


if __name__ == "__main__":
    main()
